if(NOT CMAKE_CROSSCOMPILING)
  find_package(PkgConfig QUIET)
  pkg_check_modules(PC_YAMLCPP yaml-cpp)
endif()

find_library(YAMLCPP_LIBRARY
  NAMES 
  HINTS ${HINTS_YAMLCPP_LIBDIR} ${PC_YAMLCPP_LIBDIR} ${PC_YAMLCPP_LIBRARY_DIRS}
  PATHS ${PATHS_YAMLCPP_LIBDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)
find_path(YAMLCPP_INCLUDEDIR yaml-cpp/yaml.h
  PATH_SUFFIXES yaml-cpp
  HINTS ${HINTS_YAMLCPP_INCLUDEDIR} ${PC_YAMLCPP_INCLUDEDIR} ${PC_YAMLCPP_INCLUDE_DIRS}
  PATHS ${PATHS_YAMLCPP_INCLUDEDIR}
  ${CROSSCOMPILING_NO_CMAKE_SYSTEM_PATH}
)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(YamlCpp DEFAULT_MSG YAMLCPP_INCLUDEDIR)

mark_as_advanced(YAMLCPP_INCLUDEDIR YAMLCPP_LIBRARY)

if(YAMLCPP_FOUND)
  set(YAMLCPP_INCLUDE_DIRS ${YAMLCPP_INCLUDEDIR})
  if(YAMLCPP_LIBRARY)
    set(YAMLCPP_LIBRARIES ${YAMLCPP_LIBRARY})
  else()
    set(YAMLCPP_LIBRARIES)
  endif()
endif()
